const importPlansData = {
  status: true,
  data: {
    currentPage: 1,
    data: [
      {
        updatedBy: '53930',
        columns: [
          'DB ID',
          'Surname',
          'First Name',
          'Person type',
          'DOB',
          'Birthplace',
          'Birthplace ID',
          'Birth Location',
          'Role',
          'Organisation',
          'Organisation ID',
          'Location 1',
          'Location 1 ID',
          'Location 2',
          'Location 2 ID',
          'Was student of',
          'Student of ID',
          'Has Affiliation',
          'Affiliation ID',
          'Date (Ignore)',
          'Date ID',
          'Address',
          'Address ID',
          'Source (Ignore)',
          'Source ID',
          'Thumbnail',
          'Link',
          'BirthLocation ID',
        ],
        ingestionStatus: 2,
        ingestionStartedAt: '2022-01-18T09:33:01.914Z',
        ingestionProgress: 100,
        label: '1911 Census',
        createdAt: '2022-01-18T07:44:18.929Z',
        columnsParsed: true,
        createdBy: '53930',
        ingestionCompletedAt: '2022-01-18T09:41:32.796Z',
        _id: '321335',
        relations: [
          '{"srcId":"321337","srcType":"Person","targetId":"321356","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"321338","srcType":"Temporal","targetId":"321356","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321339","srcType":"Organisation","targetId":"321356","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321340","srcType":"Spatial","targetId":"321356","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321341","targetType":"Event","relationLabel":"wasServingAs"}',
          '{"srcId":"321342","srcType":"Temporal","targetId":"321341","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321343","srcType":"Organisation","targetId":"321341","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321344","srcType":"Spatial","targetId":"321341","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321346","srcType":"Spatial","targetId":"321341","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321347","targetType":"Organisation","relationLabel":"wasStudentOf"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321348","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321349","targetType":"Event","relationLabel":"maintained"}',
          '{"srcId":"321350","srcType":"Temporal","targetId":"321349","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321351","srcType":"Organisation","targetId":"321349","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321352","srcType":"Spatial","targetId":"321349","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321353","srcType":"Spatial","targetId":"321349","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321354","targetType":"Resource","relationLabel":"isReferencedIn"}',
          '{"srcId":"321337","srcType":"Person","targetId":"321355","targetType":"Resource","relationLabel":"hasRepresentationObject"}',
        ],
        ingestionCompleteMessage: 'The ingestion completed successfully',
        uploadedFile: '321345',
        updatedAt: '2022-01-18T09:41:32.796Z',
        systemLabels: ['ImportPlan'],
      },
      {
        updatedBy: '53930',
        columns: [
          'Clericus ID',
          'Possibly the same as',
          'Name',
          'First Name',
          'Diocese',
          'Type',
          'Age',
          'When admitted to college',
          'Born',
          "Father's Occupation",
          'By whom appointed',
          'Surname',
          'Bishop ID',
          'Date of Departure',
          'How disposed of',
          'Observations',
          'Source',
          'Source ID',
        ],
        ingestionStatus: 0,
        ingestionProgress: 0,
        label: 'Byrne List 1808 (SPCM)',
        createdAt: '2022-01-13T08:50:13.053Z',
        columnsParsed: true,
        createdBy: '53930',
        _id: '97044',
        relations: [
          '{"srcId":"321320","srcType":"Person","targetId":"321321","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"321320","srcType":"Person","targetId":"321327","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"321324","srcType":"Person","targetId":"321327","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"321320","srcType":"Person","targetId":"321324","targetType":"Person","relationLabel":"servedUnder"}',
          '{"srcId":"321322","srcType":"Temporal","targetId":"321327","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321330","srcType":"Organisation","targetId":"321327","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321331","srcType":"Spatial","targetId":"321327","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321320","srcType":"Person","targetId":"321328","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"321323","srcType":"Temporal","targetId":"321328","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321320","srcType":"Person","targetId":"321329","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"321325","srcType":"Temporal","targetId":"321329","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321330","srcType":"Organisation","targetId":"321329","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321331","srcType":"Spatial","targetId":"321329","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321320","srcType":"Person","targetId":"321326","targetType":"Resource","relationLabel":"isReferencedIn"}',
          '{"srcId":"321324","srcType":"Person","targetId":"321326","targetType":"Resource","relationLabel":"isReferencedIn"}',
        ],
        ingestionCompleteMessage: '',
        uploadedFile: '321319',
        updatedAt: '2022-01-13T09:03:32.270Z',
        systemLabels: ['ImportPlan'],
      },
      {
        updatedBy: '53930',
        ingestionStatus: 0,
        columns: [
          'Clericus ID',
          'Possibly the same as',
          'Name',
          'First Name',
          'Diocese',
          'Type',
          'Age',
          'When admitted to college',
          'Born',
          "Father's Occupation",
          'By whom appointed',
          'Surname',
          'Bishop ID',
          'Date of Departure',
          'How disposed of',
          'Observations',
          'Source',
          'Source ID',
        ],
        ingestionProgress: 0,
        label: 'Byrne copy',
        createdAt: '2022-01-25T10:08:46.432Z',
        columnsParsed: true,
        createdBy: '53930',
        _id: '326419',
        relations: [
          '{"srcId":"326440","srcType":"Person","targetId":"326441","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"326440","srcType":"Person","targetId":"326447","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"326444","srcType":"Person","targetId":"326447","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"326440","srcType":"Person","targetId":"326444","targetType":"Person","relationLabel":"servedUnder"}',
          '{"srcId":"326442","srcType":"Temporal","targetId":"326447","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"326450","srcType":"Organisation","targetId":"326447","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"326451","srcType":"Spatial","targetId":"326447","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"326440","srcType":"Person","targetId":"326448","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"326443","srcType":"Temporal","targetId":"326448","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"326440","srcType":"Person","targetId":"326449","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"326445","srcType":"Temporal","targetId":"326449","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"326450","srcType":"Organisation","targetId":"326449","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"326451","srcType":"Spatial","targetId":"326449","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"326440","srcType":"Person","targetId":"326446","targetType":"Resource","relationLabel":"isReferencedIn"}',
          '{"srcId":"326444","srcType":"Person","targetId":"326446","targetType":"Resource","relationLabel":"isReferencedIn"}',
        ],
        ingestionCompleteMessage: '',
        uploadedFile: '326421',
        updatedAt: '2022-01-25T10:08:49.027Z',
        systemLabels: ['ImportPlan'],
      },
      {
        updatedBy: '53930',
        columns: [
          'DB ID',
          'Surname',
          'Alternate Surname',
          'First name',
          'First name Alternate',
          'First name Alternate Language',
          'Additional alternate first name',
          'Additional alternate language',
          'Diocese',
          'Diocese DB ID',
          'Native Place',
          'DB ID Native Place',
          'Native P alternate appellation',
          'Location Type',
          'Location Diocese',
          'DOB',
          'Birth Location',
          'Birth Location Type',
          'Birth Diocese',
          'DOD',
          'Death Location',
          'Death Location Type',
          'Death Diocese',
          'Father Surname',
          'Father First name',
          'Mother Alternate Surname (maiden name)',
          'Mother First name',
          'University',
          'Location of University',
          'Residence',
          'Residence Type',
          'Location of Residence',
          'Date of Residence',
          'Ordination',
          'Ordination Date',
          'Matriculation Date',
          'Program of Study 1',
          'Registration Date',
          'Masters of Art',
          'Program of Study 2',
          'Date of Award 2',
          'Program of Study 3',
          'Date of Award 3',
          'Program of Study 4',
          'Date of Award 4',
          'Program of Study 5',
          'Date of Award 5',
          'Other College',
          'Other College Location',
          'Program of Study Other',
          'Award Other',
          'Dates of Attendance/Award',
          'Other College 2',
          'Other College 2 Location',
          'Dates of Attendance Other 2',
          'Municipal College',
          'Dates of study Mun',
          'Bursary/Scholarship',
          'Scholarship Awarded Date',
          'Scholarship Location',
          'Minor Orders taken',
          'Minor Orders Date',
          'Minor Orders Location',
          'Minor Orders Location Type',
          'Service as PP',
          'Date',
          'PP Diocese',
          'Was Member of (Event)',
          'Date of Membership',
          'Location 2',
          'Was member of (Organisation)',
          'Was serving as (Event)',
          'Date of Service',
          'Organisation',
          'Organisation Type 2',
          'Location 3',
          'Additional Info (manual entry)',
          'Resource',
        ],
        ingestionStatus: 1,
        ingestionStartedAt: '2022-01-11T08:21:27.454Z',
        ingestionProgress: 59.70245795601552,
        label: 'Paris Toulouse',
        createdAt: '2022-01-10T09:27:30.843Z',
        columnsParsed: true,
        createdBy: '53930',
        ingestionCompletedAt: '2022-01-10T18:47:41.927Z',
        _id: '96991',
        relations: [
          '{"srcId":"96993","srcType":"Person","targetId":"96994","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"96993","srcType":"Person","targetId":"96995","targetType":"Organisation","relationLabel":"wasNativeOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"96996","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"96996","srcType":"Event","targetId":"96997","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"96998","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"96998","srcType":"Event","targetId":"96999","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97000","targetType":"Person","relationLabel":"isSonOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97001","targetType":"Person","relationLabel":"isSonOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97002","targetType":"Organisation","relationLabel":"wasStudentOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97003","targetType":"Event","relationLabel":"maintained"}',
          '{"srcId":"97003","srcType":"Event","targetId":"97006","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97003","srcType":"Event","targetId":"97004","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97003","srcType":"Event","targetId":"97005","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97006","targetType":"Organisation","relationLabel":"wasResidentOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97007","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"97007","srcType":"Event","targetId":"97008","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97009","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"97009","srcType":"Event","targetId":"97002","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97009","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97009","srcType":"Event","targetId":"97011","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97012","targetType":"Event","relationLabel":"wasRegisteredWith"}',
          '{"srcId":"97012","srcType":"Event","targetId":"97002","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97012","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97012","srcType":"Event","targetId":"97011","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97014","targetType":"Event","relationLabel":"hasRecipient"}',
          '{"srcId":"97014","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97014","srcType":"Event","targetId":"97015","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97016","targetType":"Event","relationLabel":"hasRecipient"}',
          '{"srcId":"97016","srcType":"Event","targetId":"97002","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97016","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97016","srcType":"Event","targetId":"97017","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97018","targetType":"Event","relationLabel":"hasRecipient"}',
          '{"srcId":"97018","srcType":"Event","targetId":"97002","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97018","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97018","srcType":"Event","targetId":"97019","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97020","targetType":"Event","relationLabel":"hasRecipient"}',
          '{"srcId":"97020","srcType":"Event","targetId":"97002","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97020","srcType":"Event","targetId":"97010","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97020","srcType":"Event","targetId":"97021","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97023","targetType":"Event","relationLabel":"Studied"}',
          '{"srcId":"97023","srcType":"Event","targetId":"97022","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97023","srcType":"Event","targetId":"97024","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97023","srcType":"Event","targetId":"97025","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97026","targetType":"Event","relationLabel":"hasRecipient"}',
          '{"srcId":"97026","srcType":"Event","targetId":"97022","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97026","srcType":"Event","targetId":"97024","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97026","srcType":"Event","targetId":"97025","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97027","targetType":"Organisation","relationLabel":"wasStudentOf"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97028","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"97028","srcType":"Event","targetId":"97027","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97028","srcType":"Event","targetId":"97029","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97028","srcType":"Event","targetId":"97030","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97031","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"97031","srcType":"Event","targetId":"97032","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97031","srcType":"Event","targetId":"97033","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97034","targetType":"Event","relationLabel":"wasRecordedAs"}',
          '{"srcId":"97034","srcType":"Event","targetId":"97035","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97034","srcType":"Event","targetId":"97036","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97034","srcType":"Event","targetId":"97037","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97039","targetType":"Event","relationLabel":"wasServingAs","role":71}',
          '{"srcId":"97039","srcType":"Event","targetId":"97040","targetType":"Organisation","relationLabel":"hasRelation"}',
          '{"srcId":"97039","srcType":"Event","targetId":"97042","targetType":"Spatial","relationLabel":"hasLocation"}',
          '{"srcId":"97039","srcType":"Event","targetId":"97041","targetType":"Temporal","relationLabel":"hasTime"}',
          '{"srcId":"96993","srcType":"Person","targetId":"97043","targetType":"Resource","relationLabel":"isReferencedIn"}',
        ],
        ingestionCompleteMessage: 'The ingestion completed successfully',
        uploadedFile: '96992',
        updatedAt: '2022-01-11T08:42:30.028Z',
        systemLabels: ['ImportPlan'],
      },
      {
        updatedBy: '53930',
        ingestionStatus: 0,
        columns: [
          'DB ID',
          'Surname',
          'First Name',
          'Address',
          'Address Type',
          'Address ID',
          'County',
          'Diocese 1',
          'Ordination Date',
          'Ordination Organisation',
          'Location',
          'Organisation 1',
          'Date of Entry',
          'Location 2',
          'Organisation 2',
          'Matriculation Date',
          'Location 3',
          'Was Student of 1',
          'Was Student of 2',
          'Diocese 2',
          'Resource',
          'Resource ID',
          'Thumbnail',
          'Comment',
        ],
        ingestionProgress: 0,
        label: 'st kieran',
        createdAt: '2022-01-14T11:03:20.078Z',
        columnsParsed: true,
        createdBy: '53930',
        _id: '321332',
        relations: [],
        ingestionCompleteMessage: '',
        uploadedFile: '321333',
        updatedAt: '2022-01-18T09:18:20.051Z',
        systemLabels: ['ImportPlan'],
      },
      {
        updatedBy: '53930',
        columns: [
          'DB ID',
          'Surname',
          'First Name',
          'Address',
          'Address Type',
          'Address ID',
          'County',
          'County ID',
          'Diocese 1',
          'Diocese ID',
          'Ordination Date',
          'Ordination Organisation',
          'Ordination ORG ID',
          'Location',
          'Location ID',
          'Organisation 1',
          'Date of Entry',
          'Location 2',
          'Organisation 2',
          'Matriculation Date',
          'Location 3',
          'Was Student of 1',
          'Student of ID',
          'Was Student of 2',
          'Was Student of 2 ID',
          'Diocese 2',
          'Diocese 2 ID',
          'Resource',
          'Resource ID',
          'Thumbnail',
          'Comment',
        ],
        ingestionStatus: 1,
        ingestionStartedAt: '2022-01-20T11:54:50.962Z',
        ingestionProgress: 76.97095435684648,
        label: 'st kieran public',
        createdAt: '2022-01-20T09:27:30.680Z',
        columnsParsed: true,
        createdBy: '53930',
        _id: '321556',
        relations: [
          '{"srcId":"321558","srcType":"Person","targetId":"321559","targetType":"Organisation","relationLabel":"hadAddress"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321560","targetType":"Organisation","relationLabel":"wasResidentOf"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321561","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321562","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"321563","srcType":"Temporal","targetId":"321562","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321564","srcType":"Spatial","targetId":"321562","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321565","srcType":"Organisation","targetId":"321562","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321566","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"321567","srcType":"Temporal","targetId":"321566","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321568","srcType":"Organisation","targetId":"321566","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321569","srcType":"Spatial","targetId":"321566","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321570","targetType":"Event","relationLabel":"participatedIn"}',
          '{"srcId":"321571","srcType":"Temporal","targetId":"321570","targetType":"Event","relationLabel":"isTimeOf"}',
          '{"srcId":"321572","srcType":"Organisation","targetId":"321570","targetType":"Event","relationLabel":"isRelatedTo"}',
          '{"srcId":"321573","srcType":"Spatial","targetId":"321570","targetType":"Event","relationLabel":"isLocationOf"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321574","targetType":"Organisation","relationLabel":"wasStudentOf"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321575","targetType":"Organisation","relationLabel":"wasStudentOf"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321576","targetType":"Organisation","relationLabel":"hasAffiliation"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321577","targetType":"Resource","relationLabel":"isReferencedIn"}',
          '{"srcId":"321558","srcType":"Person","targetId":"321578","targetType":"Resource","relationLabel":"hasRepresentationObject"}',
        ],
        ingestionCompleteMessage: '',
        uploadedFile: '321557',
        updatedAt: '2022-01-20T12:20:54.297Z',
        systemLabels: ['ImportPlan'],
      },
    ],
    totalItems: '6',
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};

export default importPlansData;
