export const importPlan = {
  status: true,
  data: {
    _id: '321335',
    columns: [
      'DB ID',
      'Surname',
      'First Name',
      'Person type',
      'DOB',
      'Birthplace',
      'Birthplace ID',
      'Birth Location',
      'Role',
      'Organisation',
      'Organisation ID',
      'Location 1',
      'Location 1 ID',
      'Location 2',
      'Location 2 ID',
      'Was student of',
      'Student of ID',
      'Has Affiliation',
      'Affiliation ID',
      'Date (Ignore)',
      'Date ID',
      'Address',
      'Address ID',
      'Source (Ignore)',
      'Source ID',
      'Thumbnail',
      'Link',
      'BirthLocation ID',
    ],
    columnsParsed: true,
    relations: [
      '{"srcId":"321337","srcType":"Person","targetId":"321356","targetType":"Event","relationLabel":"wasRecordedAs"}',
      '{"srcId":"321338","srcType":"Temporal","targetId":"321356","targetType":"Event","relationLabel":"isTimeOf"}',
      '{"srcId":"321339","srcType":"Organisation","targetId":"321356","targetType":"Event","relationLabel":"isRelatedTo"}',
      '{"srcId":"321340","srcType":"Spatial","targetId":"321356","targetType":"Event","relationLabel":"isLocationOf"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321341","targetType":"Event","relationLabel":"wasServingAs"}',
      '{"srcId":"321342","srcType":"Temporal","targetId":"321341","targetType":"Event","relationLabel":"isTimeOf"}',
      '{"srcId":"321343","srcType":"Organisation","targetId":"321341","targetType":"Event","relationLabel":"isRelatedTo"}',
      '{"srcId":"321344","srcType":"Spatial","targetId":"321341","targetType":"Event","relationLabel":"isLocationOf"}',
      '{"srcId":"321346","srcType":"Spatial","targetId":"321341","targetType":"Event","relationLabel":"isLocationOf"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321347","targetType":"Organisation","relationLabel":"wasStudentOf"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321348","targetType":"Organisation","relationLabel":"hasAffiliation"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321349","targetType":"Event","relationLabel":"maintained"}',
      '{"srcId":"321350","srcType":"Temporal","targetId":"321349","targetType":"Event","relationLabel":"isTimeOf"}',
      '{"srcId":"321351","srcType":"Organisation","targetId":"321349","targetType":"Event","relationLabel":"isRelatedTo"}',
      '{"srcId":"321352","srcType":"Spatial","targetId":"321349","targetType":"Event","relationLabel":"isLocationOf"}',
      '{"srcId":"321353","srcType":"Spatial","targetId":"321349","targetType":"Event","relationLabel":"isLocationOf"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321354","targetType":"Resource","relationLabel":"isReferencedIn"}',
      '{"srcId":"321337","srcType":"Person","targetId":"321355","targetType":"Resource","relationLabel":"hasRepresentationObject"}',
    ],
    ingestionStatus: 2,
    ingestionProgress: 100,
    ingestionCompleteMessage: 'The ingestion completed successfully',
    createdBy: '53930',
    createdAt: '2022-01-18T07:44:18.929Z',
    updatedBy: '53930',
    updatedAt: '2022-01-18T09:41:32.796Z',
    ingestionStartedAt: '2022-01-18T09:33:01.914Z',
    label: '1911 Census',
    ingestionCompletedAt: '2022-01-18T09:41:32.796Z',
    uploadedFile: '321345',
    uploadedFileDetails: {
      _id: '321345',
      filename: '1911Census.xlsx',
      type: 'import',
      year: 2022,
      month: 1,
      hashedName: 'a076b21b5808807acc241d2497e9a15b.xlsx',
      paths: [
        '{"path":"/Users/stavrosangelis/htdocs/ahi/clericus-neo4j/archive/imports/2022/1/1911Census/a076b21b5808807acc241d2497e9a15b.xlsx"}',
      ],
      createdBy: '53930',
      createdAt: '2022-01-18T07:49:55.288Z',
      updatedBy: '53930',
      updatedAt: '2022-01-18T07:49:55.288Z',
      label: 'undefined',
    },
  },
  error: [],
  msg: 'Query results',
};

export const importPlanRules = {
  status: true,
  data: {
    currentPage: 1,
    data: [
      {
        createdAt: '2022-01-18T07:45:05.064Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":0,"label":"[A] DB ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""},{"value":1,"label":"[B] Surname","property":"lastName","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":2,"label":"[C] First Name","property":"firstName","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":3,"label":"[D] Person type","property":"personType","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""}],"entityType":"Person"}',
        _id: '321337',
        completed: false,
        label: 'Main person/Entry',
        updatedAt: '2022-01-18T07:45:44.716Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:45:55.878Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":4,"label":"[E] DOB","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""}],"entityType":"Temporal"}',
        completed: false,
        _id: '321338',
        label: 'Date of Birth',
        updatedAt: '2022-01-18T07:46:04.845Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:46:14.489Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":5,"label":"[F] Birthplace","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":6,"label":"[G] Birthplace ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Organisation"}',
        _id: '321339',
        completed: false,
        label: 'Birthplace Organisation',
        updatedAt: '2022-01-18T07:46:28.243Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:46:41.032Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":7,"label":"[H] Birth Location","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":27,"label":"[AB] BirthLocation ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Spatial"}',
        completed: false,
        _id: '321340',
        label: 'Birth Location',
        updatedAt: '2022-01-18T07:46:57.559Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:47:10.607Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":8,"label":"[I] Role","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":28,"label":"Add custom value","property":"eventType","custom":true,"customValue":"21267","type":"number","regexp":"","prefixText":""}],"entityType":"Event"}',
        _id: '321341',
        completed: false,
        label: 'Role/Serving as Event',
        updatedAt: '2022-01-18T07:47:31.414Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:47:44.167Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":19,"label":"[T] Date (Ignore)","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""}],"entityType":"Temporal"}',
        _id: '321342',
        completed: false,
        label: 'Role/Serving as Date',
        updatedAt: '2022-01-18T07:47:54.341Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:48:05.882Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":9,"label":"[J] Organisation","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":10,"label":"[K] Organisation ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Organisation"}',
        _id: '321343',
        completed: false,
        label: 'Role/Serving as Organisation',
        importPlanId: '321335',
        updatedAt: '2022-01-18T07:48:19.236Z',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:48:33.548Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":11,"label":"[L] Location 1","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":12,"label":"[M] Location 1 ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Spatial"}',
        _id: '321344',
        completed: false,
        label: 'Role/Serving as Location 1',
        importPlanId: '321335',
        updatedAt: '2022-01-18T07:48:46.587Z',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:50:16.566Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":13,"label":"[N] Location 2","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":14,"label":"[O] Location 2 ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Spatial"}',
        _id: '321346',
        completed: false,
        label: 'Role/Serving as Location 2',
        importPlanId: '321335',
        updatedAt: '2022-01-18T07:50:32.339Z',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:50:42.824Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":15,"label":"[P] Was student of","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":16,"label":"[Q] Student of ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""},{"value":15,"label":"[P] Was student of","property":"condition","custom":false,"customValue":"","type":"condition","regexp":"","prefixText":""}],"entityType":"Organisation"}',
        _id: '321347',
        completed: false,
        label: 'Was Student of Organisation',
        importPlanId: '321335',
        updatedAt: '2022-01-18T07:51:03.294Z',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:51:15.965Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":17,"label":"[R] Has Affiliation","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":18,"label":"[S] Affiliation ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""},{"value":17,"label":"[R] Has Affiliation","property":"condition","custom":false,"customValue":"","type":"condition","regexp":"","prefixText":""}],"entityType":"Organisation"}',
        _id: '321348',
        completed: false,
        label: 'Had Affiliation Organisation',
        updatedAt: '2022-01-18T07:51:35.375Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:51:49.818Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":28,"label":"Add custom value","property":"eventType","custom":true,"customValue":"72761","type":"number","regexp":"","prefixText":""},{"value":28,"label":"Add custom value","property":"label","custom":true,"customValue":"Residence","type":"string","regexp":"","prefixText":""}],"entityType":"Event"}',
        _id: '321349',
        completed: false,
        label: 'Habitation Event',
        updatedAt: '2022-01-18T07:52:12.455Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:52:25.527Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":19,"label":"[T] Date (Ignore)","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""}],"entityType":"Temporal"}',
        _id: '321350',
        completed: false,
        label: 'Habitation Date',
        updatedAt: '2022-01-18T07:52:34.999Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:52:45.765Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":9,"label":"[J] Organisation","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":10,"label":"[K] Organisation ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Organisation"}',
        _id: '321351',
        completed: false,
        label: 'Habitation Organisation',
        updatedAt: '2022-01-18T07:53:06.581Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:53:21.014Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":21,"label":"[V] Address","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":22,"label":"[W] Address ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Spatial"}',
        _id: '321352',
        completed: false,
        label: 'Habitation Location',
        updatedAt: '2022-01-18T07:53:37.088Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:53:48.600Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":11,"label":"[L] Location 1","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":12,"label":"[M] Location 1 ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Spatial"}',
        _id: '321353',
        completed: false,
        label: 'Habitation Location 2',
        updatedAt: '2022-01-18T07:54:03.815Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:54:19.472Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":23,"label":"[X] Source (Ignore)","property":"label","custom":false,"customValue":"","type":"string","regexp":"","prefixText":""},{"value":24,"label":"[Y] Source ID","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Resource"}',
        completed: false,
        _id: '321354',
        label: 'Source',
        updatedAt: '2022-01-18T07:54:34.854Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:54:47.489Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":25,"label":"[Z] Thumbnail","property":"_id","custom":false,"customValue":"","type":"_id","regexp":"","prefixText":""}],"entityType":"Resource"}',
        completed: false,
        _id: '321355',
        label: 'Thumbnail',
        updatedAt: '2022-01-18T07:54:56.479Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
      {
        createdAt: '2022-01-18T07:55:09.316Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"columns":[{"value":28,"label":"Add custom value","property":"eventType","custom":true,"customValue":"59249","type":"number","regexp":"","prefixText":""},{"value":28,"label":"Add custom value","property":"label","custom":true,"customValue":"Born","type":"string","regexp":"","prefixText":""}],"entityType":"Event"}',
        completed: false,
        _id: '321356',
        label: 'Birth Event',
        updatedAt: '2022-01-18T07:55:26.338Z',
        importPlanId: '321335',
        systemLabels: ['ImportRule'],
      },
    ],
    totalItems: '19',
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};

export const dataCleaningInstance = {
  status: true,
  data: {
    currentPage: 1,
    data: [
      {
        createdAt: '2022-02-03T16:35:47.681Z',
        updatedBy: '53930',
        createdBy: '53930',
        rule:
          '{"type":"unique","columns":[{"value":0,"label":"[A] DB ID"}],"entityType":""}',
        label: 'data cleaning instance',
        completed: false,
        _id: '100441',
        type: 'unique',
        updatedAt: '2022-02-03T16:40:00.125Z',
        importPlanId: '41226',
        systemLabels: ['DataCleaning'],
      },
    ],
    totalItems: '1',
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};
